GET http://localhost:4000/posts

###

POST http://localhost:4000/posts
Content-Type: application/json

{
  "title": "My First Post"
}

###

###
GET http://localhost:4001/posts/123/comments

###
POST http://localhost:4001/posts/123/comments
Content-Type: application/json

{
  "content": "Great post!1"
}